{% set version = "0.5" %}
{% set patchlevel = "p0" %}
{% set name = "sagemath-db-conway-polynomials" %}

package:
  name: {{ name }}
  version: {{ version }}.{{ patchlevel }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://files.sagemath.org/spkg/upstream/conway_polynomials/conway_polynomials-{{ version }}.tar.bz2
  sha256: d8f2788a85b1c2482cc4abe1a35d3da777445e21ec49b031d36b899e3c0deb17

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - python
    - six
    - curl
  run:
    - python
    - six

test:
  commands:
    - test -f "$PREFIX/share/conway_polynomials/conway_polynomials.p"

about:
  home: http://github.com/sagemath/sage
  license: GPLv3
  summary: sagemath-db-conway-polynomials contains a small database of Conway polynomials.

extra:
  recipe-maintainers:
    - isuruf
