travis:
  secure:
    BINSTAR_TOKEN: ZrsqJ06dci9UwlV5XI+ZqOjQxMVRZYxzZyutD0DniAaajBhcIlNzJT6o3v38jl5PmeklT0w4r4L8NV1Hu0sJqdkuj48pDX7J6ddXXmoLJWKyqverWIej2h972vSj0nXn57P0CGaCWDUsPklLHhO0BrPSJ0nxfxWA6kQaHrt/0BzBm7KBdf37g5AfoqpNK67XlSoIKPJbsq15VrEsMU61wVty3CqW2/HumE5xZDuu8ons0uJt4W5Itnb9aNXXqU9cHb/9gns5e/SgRAMgUIlNCFd41hN5kJ3g2bgvuVALr1jRTlsNync920tJ+shgTQ6vPt6CL1WGdfLWXdLKV3nq2X7RPrOg4Eb1PFRx+6r7gyFcw4mAWH+ezjZ7rYkNnk5TWr5+AaiFYXgstq8hQuZcF9sKkxvQjv9PNwDaHoCQVSMuEBaDng+1S2dWuNEJk22WPjA71Q9PU6Vyx8yuHuqFtRbBkX5ractJvAxJ74dR+bUfZxZE/pFc15GW20fcgBg2OLWqztV6hfS8/XnLrhBVEhxAdexGujQWLVexBZVZa18ZT3GNW8bufsLwaWEAm3z1iotycuDqtWYXAkFvhUKRZGp4XvkeTlzLCFViYd7ZJ24XRifefQb//a60hIWnFaD8dCEKjVdVEdIHjbFbtzZZuI8LNw0jqo3isaVi27XtTNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
